run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions and types
    
    # Additional recommended linters
    - bodyclose     # Check HTTP response body is closed
    - dupl          # Code clone detection
    - exportloopref # Check for pointers to enclosing loop variables
    - gochecknoinits # Check no init functions
    - goconst       # Find repeated strings that could be constants
    - gocritic      # The most opinionated Go linter
    - gocyclo       # Cyclomatic complexity
    - gofmt         # Check code is gofmt-ed
    - goimports     # Check import statements are formatted
    - gosec         # Security problems
    - misspell      # Spelling mistakes
    - nolintlint    # Ill-formed or insufficient nolint directives
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - stylecheck    # Replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - whitespace    # Detection of leading and trailing whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - flagDeref
      - ifElseChain
      - methodExprCall
      - nilValReturn
      - octalLiteral
      - rangeExprCopy
      - rangeValCopy
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      - valSwap
      - weakCond
  
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    # Exclude duplicate code detection in test helpers
    - path: tests/testutil
      linters:
        - dupl
    
    # Exclude init function checks for main package
    - path: cmd/
      linters:
        - gochecknoinits

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
